### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by alekseykulikov**
Full rewrite with the goal to make **IndexedDB mainstream by giving consistent API across all modern browsers**, by providing:
- automated tests in all supported browsers using zuul and sauselabs.
- use and support Safari 9+ and fallback to WebSQL on early versions
- separate code on small, testable modules
- use modern technologies: ES2015 + babel, async/await syntax, eslint
- highly rely on [official specification](https://github.com/w3c/IndexedDB) and implement some features from 2.0 (like getAll and "close" event)
- support plugins by using default IndexedDB APIs.

Notable changes:
- [x] use ES2015 Promise by default
- [x] official support for IE10+, Safari 6+, Firefox, Chrome, Opera, Android 4.4+
- [x] remove support for synchronous open and make `Schema` optional
- [x] add namespaces, ex: `db.books.byIndex`
- [x] deprecate `.all()` and add `.getAll(range, opts)`, which supports `limit`, `offset`, `reverse`, and `unique` options
- [x] add `.openCursor(range, [direction])` instead of `.cursor()` as low level proxy to native implementation
- [x] `.count([range])` accepts optional key range [#30](https://github.com/treojs/treo/issues/30)
- [x] add `store.add([key], val)`
- [x] remove support for transactions and `db.transaction([storeNames], mode)` [#34](https://github.com/treojs/treo/issues/34)
- [x] add array/object batch syntax notation [#39](https://github.com/treojs/treo/issues/39)
- [x] rename `db.drop()` to `db.del()` + fixed fails in Safari [#33](https://github.com/treojs/treo/issues/33)
- [x] remove bower & component support
- [x] full rewrite on ES2015 using babel@6
- [x] add automated unit tests using zuul, saucelabs
- [x] use `eslint` for code style validation using `eslint-config-airbnb`
- [x] move to [treojs](https://github.com/treojs) organization
- [x] extract modules [idb-schema](https://github.com/treojs/idb-schema), [idb-factory](https://github.com/treojs/idb-factory), [idb-batch](https://github.com/treojs/idb-batch), [idb-request](https://github.com/treojs/idb-request) [treo-websql](https://github.com/treojs/treo-websql)
- [ ] new docs

### CODE REVIEW

**Comment by alekseykulikov** [comment]
This is a pre-relis before 1.0.0, and the final API is:

```js
var treo = require('treo');

// alternative to window.indexedDB
treo('name', schema); // schema contains information about database
treo.schema(); // create idb-schema
treo.Database;
treo.Transaction;
treo.Store;
treo.Index;
treo.Promise = require('es6-promise'); // change Promise library

// Database represents connection to a database
db.on('error', 'abort', 'versionchange');
db.transaction([name, name], mode); // create transaction
async db.close(); // database might be in opening state
async db.del(); // close && deleteDatabase (avoid onversionchange)
db.name; // getter
db.version; // getter
db.stores; // getter
db.use(fn); // use plugin fn(db, treo)
db.store(name); // create store with automatic transactions

// Store is the primary mechanism for storing data.
async store.get(key); // returns undefined when record does not exists
async store.getAll([range]); // array
async store.put(key, val); // out-of-line keys
async store.put(obj); // in-line keys with keyPath
async store.del(key); // store.delete
async store.batch(ops); // best way to reuse transaction
async store.count([range]);
async store.clear();
async store.cursor([key], [direction], fn); // low level
store.index(name); // new Index()
store.name; // getter
store.key; // getter
store.indexes; // getter to array of index names

// Index allows to looking up records in a store using properties of the values
async index.get(key); // undefined if record does not exist
async index.getAll([range]);
async index.count([range]);
async index.cursor([key], [direction], fn); // low level
index.name; // getter
index.key; // getter
index.unique; // getter
index.multi; // getter

// Transaction represents atomic operation on data (uses internally)
tr.on('error', 'abort', 'complete');
tr.store(name); // use store in current transaction
tr.abort();
tr.mode; // getter
async tr; // thenable
```

I would like to get feedback for all this changes :)
/cc @unkillbob @capsula4 @robertfall @lukerandall @adriengibrat

**Comment by lukerandall** [comment]
:+1: to using promises by default. This looks good to me.

**Comment by robertfall** [comment]
:+1: 

I like this:

> index.get(range) separated on 2 methods:
  > * index.get(key) always returns first value and accepts only keys
  > * index.getAll([range]) always returns an array

**Comment by unkillbob** [comment]
:+1: API looks great!

**Comment by adriengibrat** [comment]
:+1: nice and consistent API

**Comment by hawkrives** [comment]
Is there anything I can help out with towards either 0.6 or 1.0? Your checklist up top looks like it just needs a README and some docs. I'd be happy to contribute some time towards this library.

**Comment by alekseykulikov** [comment]
@hawkrives thank you for really generous suggestion.

Todo list on top is outdated. 
Beside minor improvements and refines, documentation and better unit tests are main issues. I will try to find time on this weekend and update it, and than let you know about specific things you could help. 

Merging this PR is really bothering task in my todo list. Thank you for reminder to take some action :)

**Comment by wclr** [comment]
Is 6 ready for use except docs? I don't see there websql fallback.

**Comment by alekseykulikov** [comment]
@whitecolor yes, websql fallback is https://github.com/treojs/treo-websql

**Comment by wclr** [comment]
@alekseykulikov great thanks)

**Comment by wclr** [comment]
@alekseykulikov should be used from github, no npm version yet? (0.6.0-rc2 seem a bit old)

**Comment by alekseykulikov** [comment]
@whitecolor yes 0.6.0-rc2 is outdated, you can install current pre-relase verion with `npm i treo@1.0.0-beta` and use https://github.com/treojs/treo/tree/0.6.0 as docs reference.

**Comment by wclr** [comment]
@alekseykulikov great, why you are not including `dist` in npm package? It could be useful (or even needed) for some browser loaders like `System.js`

**Comment by alekseykulikov** [comment]
@whitecolor I use npm/browserify for all my frontend and not really sure how other loaders work. But I can add it, it's just a change in package.json

``` json
"files": [
  "dist",
  "lib"
]
```

Does it require any additional fields, and what do you refer as `System.js`?

Also having a `/dist` folder can be bower alternative.

``` html
<script src="/node_modules/treo/dist/treo.min.js"></script>
```

**Comment by wclr** [comment]
for now including `dist` folder would be enough [System.js loader](https://github.com/systemjs/systemjs) or based on it [Steal](https://github.com/stealjs/steal) load ES6/CJS/AMD modules in browser without bundling. Sometimes (often) it is better for them to load already browserfied versions of modules.

**Comment by xori** [comment]
It would be great to see this merged, and would love to help in any way if I can.

**Pull request closed without merging**
