### PR TITLE
Bump dependencies to latest idb-schema and idb-range

### PR DESCRIPTION
**Pull request by unkillbob**
Keen to get 0.6 work back underway and in the process of testing 0.6 RC2 in our environment I identified these out of date dependencies.

Not sure if any additional work needs to be done here as there's no release notes for either idb-schema or idb-range so not sure if there's been any API breakages in their respective 3.x major releases.

Also `npm test` is reporting 0 tests for so not sure if I've broken something there or not?

### CODE REVIEW

**Comment by alekseykulikov** [comment]
`0 tests` are actually not good :) 
3.x releases have some breaking changes and the main intention is to move to ES6. So for 0.6 RC2 dep update is not necessary. I'm working on the next release, but there're still some things to do.

**Comment by unkillbob** [comment]
> 0 tests are actually not good :) 

Ok cool there must be something broken then, will dig in and have a look.

> So for 0.6 RC2 dep update is not necessary.

There are some bug fixes in the 3.x releases though (e.g. the fix to MS Edge/IE support) that I wanted to get. Everything else in our application is working fine on 0.6 RC2.

**Comment by unkillbob** [comment]
> I'm working on the next release, but there're still some things to do.

How can I help :)?

**Comment by alekseykulikov** [comment]
> How can I help :)?

Nice to hear, I think a Skype call will be faster, I'm `alekseys.kulikov`.

**Comment by alekseykulikov** [comment]
with this pull request, the main problem, that [since 3.x](https://github.com/treojs/idb-schema/blob/master/History.md#300--2015-11-03) it's not possible to call Schema without new, so the fix should be:

``` js
exports.schema = function() { return new Schema() }
```

**Comment by unkillbob** [comment]
Struggling to figure out the unit test failure:

```
Database #on "error"
    ✘ done() called multiple times
```

The first time the error handler is called it is correctly the constraint violation exception, the second time there isn't an error message but the target seems to be the database (not the transaction as in the first one). Perhaps an error is thrown trying to close the database?

Only seems to happen on phantomjs...

**Comment by alekseykulikov** [comment]
The reason it calls 2 times, because [Indexeddbshim@2.2.1](https://github.com/axemclion/IndexedDBShim/issues/205) fixes onerror callback, but treo-websql, still polyfills it https://github.com/treojs/treo-websql/blob/master/lib/index.js#L71

Good news: I'm eventually finishing 0.6.0 and will release it in the end of this week or on next week. Main changes with 0.6.0-rc2:
- remove `Transaction` object (for now). It brings too much inconsistency between browsers, and can't be used really anywhere except chrome
- full rewrite with ES6 and CI testing in Saucelabs, that applies to all treo's family modules, ex: https://github.com/treojs/idb-schema
- add support for namespaces, ex: `db.books.byAuthor`
- remove support for bower and component, now it supports only npm and standalone builds
- dependencies upgrade (I close this PR)
- treo-polyfill, which fixes [all Safari issues](https://gist.github.com/nolanlawson/08eb857c6b17a30c1b26), improves IndexedDBShim and fixes IE.

I also defined a goal of the project. **The goal of treo is to make IndexedDB mainstream by giving consistent API across all modern browsers.**

As usual I need help with documentation and feedback.
I have excited plans for 1.0.0, which should come a couple weeks after 0.6.0.

**Pull request closed without merging**
